CREATE TABLE TGT_EXP_TESTTHREE( 
CUSTOMER_ID varchar(30),
IPS_CUSTOMER_ID_NUM varchar(30),
INDUSTRY_ID varchar(100),
CLAIM_ID varchar(30),
CLAIM_DESC varchar(2000),
LOB_ID varchar(30),
COUNTRY_ID varchar(50)
);
