CREATE TABLE TGT_EXP_TESTTWO( 
TYPE_OF_EVENT_ID1 varchar(70),
TYPE_OF_VEHICLE1 varchar(30),
TYPE_OF_COVERAGE1 varchar(30),
CLAIM_STATUS_ID1 varchar(10),
CONTRACT_ID1 varchar(30),
PROGRAM_ID1 varchar(30),
YEAR_ID1 decimal(4),
INSURED_F1 decimal(30),
TOTAL_VEHICLES_F_OD1 decimal(30),
TOTAL_VEHICLES_F_TPL1 decimal(30),
RUN_ID1 integer(10)
);
