CREATE TABLE TGT_RTR_TESTONE( 
CUSTOMER_ID varchar(30),
IPS_CUSTOMER_ID_NUM varchar(30),
INDUSTRY_ID varchar(100),
CLAIM_ID varchar(30),
CLAIM_DESC varchar(2000),
LOB_ID varchar(30),
COUNTRY_ID varchar(50),
TYPE_OF_EVENT_ID varchar(70),
TYPE_OF_VEHICLE varchar(30),
TYPE_OF_COVERAGE varchar(30),
CLAIM_STATUS_ID varchar(10),
CONTRACT_ID varchar(30),
PROGRAM_ID varchar(30),
YEAR_ID decimal(4),
INSURED_F decimal(30),
TOTAL_VEHICLES_F_OD decimal(30),
TOTAL_VEHICLES_F_TPL decimal(30),
RUN_ID integer(10)
);
